name = "kuesioner-nomophobia"
main = "src/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "nomophobia-database"
database_id = "754bce3a-2650-4838-996b-2ba002d8cd73"

[[r2_buckets]]
binding = "SCREENTIME_BUCKET"
bucket_name = "nomophobia-screentime"

[vars]
QUESTIONNAIRE_EXPORT_TOKEN = "2744b6e9bd5477e06afe853f8d4c812a"
